### ISSUE TITLE
注册接口

### ISSUE THREAD

**Issue by AntiO2** [GlimmerIndex/Glimmer-Index-Back-End#1]

**Comment by sudheesanamp2003** [comment]
i will do it

**Comment by AntiO2** [comment]
> 

thanks for your enthusiasm, but I have finished it already. lol

**Comment by AntiO2** [comment]
[feat register](https://github.com/GlimmerIndex/Glimmer-Index-Back-End/commit/7d76f44570eda5e7a2e16888ac0237558a65fd39)
